version: '2'
services:
    crazyapp-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/CrazyApp/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_ROOT_HOST=%
            - MYSQL_USER=demo
            - MYSQL_PASSWORD=password
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=demo
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --max_allowed_packet=32505856
#    crazyapp-phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        # volumes:
#        #     - ~/volumes/jhipster/iquitosApp/mysql/:/var/lib/mysql/
#        environment:
#            - MYSQL_USER=root
#            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#            - MYSQL_DATABASE=crazyapp
#            - PMA_HOST=crazyapp-mysql
#        ports:
#            - 8181:80
